import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import NavigationBar from '../components/NavigationBar';
import Footer from '../components/Footer';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const MachineReport = () => {
    const [machines, setMachines] = useState([]);

    useEffect(() => {
        axios
            .get('http://localhost:5555/machines')
            .then((response) => {
                setMachines(response.data.data);
            })
            .catch((error) => {
                console.log(error);
            });
    }, []);

    const formatDate = (date) => {
        const formattedDate = new Date(date);
        return formattedDate.toISOString().split('T')[0];
    };

    const handleDownloadPdf = () => {
        const doc = new jsPDF('landscape', 'mm', 'a4');

        // Title and header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.text('Machine Report', 148.5, 20, { align: 'center' });

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);

        // Table headers and data
        const headers = [
            ['Machine Number', 'Machine Name', 'Machine Type', 'Installation Date', 'Warranty Information', 'Status']
        ];
        
        const data = machines.map(machine => [
            machine.machineNumber,
            machine.machineName,
            machine.machineType,
            formatDate(machine.installationDate),
            machine.warrentyInformation,
            machine.Status
        ]);

        doc.autoTable({
            startY: 30,
            head: headers,
            body: data,
            styles: {
                fontSize: 10,
                cellPadding: 4,
                halign: 'left',
                valign: 'middle'
            },
            headStyles: {
                fillColor: [22, 160, 133],
                textColor: [255, 255, 255],
                fontStyle: 'bold'
            },
            alternateRowStyles: {
                fillColor: [245, 245, 245]
            },
            columnStyles: {
                3: { halign: 'center' } // Center-align installation date
            },
            theme: 'grid'
        });

        // Footer
        doc.setFontSize(10);
        doc.text('Generated by Your Company', 10, doc.internal.pageSize.height - 10);
        doc.text(`Generated on: ${new Date().toISOString().split('T')[0]}`, doc.internal.pageSize.width - 40, doc.internal.pageSize.height - 10, { align: 'right' });

        // Save the PDF
        doc.save('machine_report.pdf');
    };

    return (
        <div className="flex flex-col min-h-screen">
            <NavigationBar />
            <nav className="bg-green-500 p-4">
                <div className="container mx-auto flex justify-center">
                    <div className="flex space-x-4">
                        <Link to="/" className="text-white hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Home</Link>
                        <Link to="/MachineHome" className="text-white hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Machines</Link>
                        <Link to="/machines/creates" className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Create Machine</Link>
                        <Link to="/MachineReport" className="text-white bg-gray-900 hover:bg-gray-700 px-3 py-2 rounded-md text-sm font-medium">Machine Report</Link>
                    </div>
                </div>
            </nav>
            
            <div className="flex justify-between items-center p-4">
                <h1 className="text-3xl font-bold">Machine Report</h1>
                <button onClick={handleDownloadPdf} className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg">
                    Download PDF
                </button>
            </div>
            
            <div className="flex-grow p-4">
                <div id="machine-table" className="overflow-x-auto bg-white rounded-lg shadow-lg">
                    <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-100">
                            <tr>
                                <th className="px-6 py-3 text-left text-sm font-medium text-gray-600 uppercase tracking-wider">Machine Number</th>
                                <th className="px-6 py-3 text-left text-sm font-medium text-gray-600 uppercase tracking-wider">Machine Name</th>
                                <th className="px-6 py-3 text-left text-sm font-medium text-gray-600 uppercase tracking-wider">Machine Type</th>
                                <th className="px-6 py-3 text-left text-sm font-medium text-gray-600 uppercase tracking-wider">Installation Date</th>
                                <th className="px-6 py-3 text-left text-sm font-medium text-gray-600 uppercase tracking-wider">Warranty Information</th>
                                <th className="px-6 py-3 text-left text-sm font-medium text-gray-600 uppercase tracking-wider">Status</th>
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-200">
                            {machines.map(machine => (
                                <tr key={machine._id} className="hover:bg-gray-50">
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{machine.machineNumber}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{machine.machineName}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{machine.machineType}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{formatDate(machine.installationDate)}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{machine.warrentyInformation}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{machine.Status}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
            
            {/* Add the footer at the bottom of the page */}
            <div className="mt-auto">
                <Footer />
            </div>
        </div>
    );
};

export default MachineReport;
